// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef UI_ALARM_H
#define UI_ALARM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Alarm
extern void ui_Alarm_screen_init(void);
extern void ui_Alarm_screen_destroy(void);
extern void ui_event_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_Alarm_container;
extern lv_obj_t * ui_Set_alarm;
extern lv_obj_t * ui_Alarm_Comp;
extern lv_obj_t * ui_Alarm_Comp1;
extern lv_obj_t * ui_Alarm_Comp2;
extern lv_obj_t * ui_Alarm_Comp3;
extern lv_obj_t * ui_Scrolldots5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

