// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef UI_CHAT_H
#define UI_CHAT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Chat
extern void ui_Chat_screen_init(void);
extern void ui_Chat_screen_destroy(void);
extern void ui_event_Chat(lv_event_t * e);
extern lv_obj_t * ui_Chat;
extern lv_obj_t * ui_Chat_container;
extern lv_obj_t * ui_Chat_date;
extern lv_obj_t * ui_C1;
extern lv_obj_t * ui_Chat_Panel1;
extern lv_obj_t * ui_Chat1;
extern lv_obj_t * ui_Chat_Icon1;
extern lv_obj_t * ui_C2;
extern lv_obj_t * ui_Chat_Panel2;
extern lv_obj_t * ui_Chat2;
extern lv_obj_t * ui_Chat_Icon2;
extern lv_obj_t * ui_Delifered;
extern lv_obj_t * ui_C3;
extern lv_obj_t * ui_Chat_Panel3;
extern lv_obj_t * ui_Chat3;
extern lv_obj_t * ui_Chat_Icon3;
extern lv_obj_t * ui_Scrolldots2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

