// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Call = NULL;
lv_obj_t * ui_Elena = NULL;
lv_obj_t * ui_Incoming = NULL;
lv_obj_t * ui_Call_Incon1 = NULL;
lv_obj_t * ui_Phone1 = NULL;
lv_obj_t * ui_Call_Incon2 = NULL;
lv_obj_t * ui_Phone2 = NULL;
lv_obj_t * ui_Avatar = NULL;
lv_obj_t * ui_Scrolldots1 = NULL;
// event funtions
void ui_event_Call(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Avatar, 100);
        upanim_Animation(ui_Elena, 200);
        upanim_Animation(ui_Incoming, 300);
        upanim_Animation(ui_Call_Incon1, 200);
        upanim_Animation(ui_Call_Incon2, 300);
        scrolldot_Animation(ui_Scrolldots1, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Chat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Chat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Call_screen_init(void)
{
    ui_Call = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Call, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Call, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Call, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Call, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Elena = ui_Small_Label_create(ui_Call);
    lv_obj_set_x(ui_Elena, 0);
    lv_obj_set_y(ui_Elena, 0);
    lv_obj_set_align(ui_Elena, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Elena, "Elena Smith Bergman");
    lv_obj_set_style_text_color(ui_Elena, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Elena, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Incoming = ui_Small_Label_create(ui_Call);
    lv_obj_set_x(ui_Incoming, 0);
    lv_obj_set_y(ui_Incoming, 25);
    lv_obj_set_align(ui_Incoming, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Incoming, "Incoming Call");
    lv_obj_set_style_text_color(ui_Incoming, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Incoming, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Call_Incon1 = lv_obj_create(ui_Call);
    lv_obj_set_width(ui_Call_Incon1, 60);
    lv_obj_set_height(ui_Call_Incon1, 60);
    lv_obj_set_x(ui_Call_Incon1, -50);
    lv_obj_set_y(ui_Call_Incon1, -42);
    lv_obj_set_align(ui_Call_Incon1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Call_Incon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Call_Incon1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon1, lv_color_hex(0xE63431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call_Incon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Call_Incon1, lv_color_hex(0xE63431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Call_Incon1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Call_Incon1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Call_Incon1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Call_Incon1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Call_Incon1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon1, lv_color_hex(0xFF5855), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Call_Incon1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Phone1 = lv_image_create(ui_Call_Incon1);
    lv_image_set_src(ui_Phone1, &ui_img_phone_png);
    lv_obj_set_width(ui_Phone1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Phone1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Phone1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Phone1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Phone1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Phone1, 1360);

    ui_Call_Incon2 = lv_obj_create(ui_Call);
    lv_obj_set_width(ui_Call_Incon2, 60);
    lv_obj_set_height(ui_Call_Incon2, 60);
    lv_obj_set_x(ui_Call_Incon2, 50);
    lv_obj_set_y(ui_Call_Incon2, -42);
    lv_obj_set_align(ui_Call_Incon2, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Call_Incon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Call_Incon2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon2, lv_color_hex(0x10D262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call_Incon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Call_Incon2, lv_color_hex(0x10D262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Call_Incon2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Call_Incon2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Call_Incon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Call_Incon2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Call_Incon2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon2, lv_color_hex(0x31EF81), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Call_Incon2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Phone2 = lv_image_create(ui_Call_Incon2);
    lv_image_set_src(ui_Phone2, &ui_img_phone_png);
    lv_obj_set_width(ui_Phone2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Phone2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Phone2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Phone2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Phone2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Avatar = lv_image_create(ui_Call);
    lv_image_set_src(ui_Avatar, &ui_img_avatar_png);
    lv_obj_set_width(ui_Avatar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avatar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avatar, 0);
    lv_obj_set_y(ui_Avatar, 20);
    lv_obj_set_align(ui_Avatar, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Avatar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Avatar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Avatar, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Avatar, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Avatar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Avatar, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Avatar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Avatar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Avatar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scrolldots1 = ui_Scrolldots_create(ui_Call);
    lv_obj_set_x(ui_Scrolldots1, 0);
    lv_obj_set_y(ui_Scrolldots1, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 11);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Call, ui_event_Call, LV_EVENT_ALL, NULL);

}

void ui_Call_screen_destroy(void)
{
    if(ui_Call) lv_obj_del(ui_Call);

    // NULL screen variables
    ui_Call = NULL;
    ui_Elena = NULL;
    ui_Incoming = NULL;
    ui_Call_Incon1 = NULL;
    ui_Phone1 = NULL;
    ui_Call_Incon2 = NULL;
    ui_Phone2 = NULL;
    ui_Avatar = NULL;
    ui_Scrolldots1 = NULL;

}
