// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef UI_CALL_H
#define UI_CALL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Call
extern void ui_Call_screen_init(void);
extern void ui_Call_screen_destroy(void);
extern void ui_event_Call(lv_event_t * e);
extern lv_obj_t * ui_Call;
extern lv_obj_t * ui_Elena;
extern lv_obj_t * ui_Incoming;
extern lv_obj_t * ui_Call_Incon1;
extern lv_obj_t * ui_Phone1;
extern lv_obj_t * ui_Call_Incon2;
extern lv_obj_t * ui_Phone2;
extern lv_obj_t * ui_Avatar;
extern lv_obj_t * ui_Scrolldots1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

