// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef UI_MUSIC_PLAYER_H
#define UI_MUSIC_PLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Music_Player
extern void ui_Music_Player_screen_init(void);
extern void ui_Music_Player_screen_destroy(void);
extern void ui_event_Music_Player(lv_event_t * e);
extern lv_obj_t * ui_Music_Player;
extern lv_obj_t * ui_Music_Title;
extern lv_obj_t * ui_Author;
extern lv_obj_t * ui_Play_btn;
extern lv_obj_t * ui_Play;
extern lv_obj_t * ui_Album;
extern lv_obj_t * ui_Backward;
extern lv_obj_t * ui_Forward;
extern lv_obj_t * ui_Scrolldots3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

