// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_Demo = NULL;
lv_obj_t * ui_Smart_Gadget = NULL;
lv_obj_t * ui_SLS_Logo = NULL;
// event funtions
void ui_event_Splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SLS_Logo, 100);
        upanim_Animation(ui_Smart_Gadget, 200);
        upanim_Animation(ui_Demo, 300);
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1400, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Demo = ui_Small_Label_create(ui_Splash);
    lv_obj_set_x(ui_Demo, 0);
    lv_obj_set_y(ui_Demo, 75);
    lv_obj_set_align(ui_Demo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Demo, "Demo");
    lv_obj_set_style_text_color(ui_Demo, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Demo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Smart_Gadget = ui_Small_Label_create(ui_Splash);
    lv_obj_set_x(ui_Smart_Gadget, 0);
    lv_obj_set_y(ui_Smart_Gadget, 50);
    lv_obj_set_align(ui_Smart_Gadget, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Smart_Gadget, "Smart Gadget");
    lv_obj_set_style_text_color(ui_Smart_Gadget, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Smart_Gadget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLS_Logo = lv_image_create(ui_Splash);
    lv_image_set_src(ui_SLS_Logo, &ui_img_sls_logo_png);
    lv_obj_set_width(ui_SLS_Logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLS_Logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SLS_Logo, 0);
    lv_obj_set_y(ui_SLS_Logo, -50);
    lv_obj_set_align(ui_SLS_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SLS_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_SLS_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    ui_Demo = NULL;
    ui_Smart_Gadget = NULL;
    ui_SLS_Logo = NULL;

}
