// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Weather
extern void ui_Weather_screen_init(void);
extern void ui_Weather_screen_destroy(void);
extern void ui_event_Weather(lv_event_t * e);
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Pary_Cloud;
extern lv_obj_t * ui_New_York;
extern lv_obj_t * ui_Cloud;
extern lv_obj_t * ui_Celsius;
extern lv_obj_t * ui_Weather_Icons;
extern lv_obj_t * ui_w1;
extern lv_obj_t * ui_w2;
extern lv_obj_t * ui_w3;
extern lv_obj_t * ui_W1_Num;
extern lv_obj_t * ui_W2_Num;
extern lv_obj_t * ui_W3_Num;
extern lv_obj_t * ui_Scrolldots4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

